# Generated by Django 2.0.6 on 2018-08-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20180815_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airport',
            name='id',
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_code',
            field=models.CharField(default='BWI', max_length=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
