# Generated by Django 2.0.6 on 2018-08-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20180815_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='partner_logo',
        ),
    ]
