# Generated by Django 2.0.6 on 2018-08-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_user_card_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='card_account_id',
            field=models.CharField(default='NOT YET IMPLEMENTED', max_length=50),
        ),
    ]
