# Generated by Django 2.0.6 on 2018-08-17 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_auto_20180817_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=50)),
                ('premium_expected', models.BooleanField(default=False)),
                ('prefered_gas_type', models.CharField(max_length=50)),
                ('hybrid', models.BooleanField(default=False)),
                ('primary_auto', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AutoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('classification', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='auto_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.AutoType'),
        ),
        migrations.AddField(
            model_name='auto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User'),
        ),
    ]
