# Generated by Django 2.0.6 on 2018-08-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_auto_20180817_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_rate_park_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_rent_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_valet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_wash', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_detail', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_basic_cleaning_for_sublet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_itinerary_change_return_to_owner', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_itinerary_change_per_mile_over_30_miles', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_valet_commission_park', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_valet_commission_terminal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_valet_commission_fueling', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_valet_commission_itinerary_change_return', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_valet_commission_empty_trip', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_tax_1', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_tax_2', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_percent_sublet_paid_to_partner', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_rate_percent_sublet_paid_to_auto_owner', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('airport_promotion_points', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_park_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_rent_day', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_valet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_wash', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_detail', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_basic_cleaning_for_sublet', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_itinerary_change_return_to_owner', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_itinerary_change_per_mile_over_30_miles', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_valet_commission_park', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_valet_commission_terminal', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_valet_commission_fueling', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_valet_commission_itinerary_change_return', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_valet_commission_empty_trip', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_percent_sublet_paid_to_partner', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('partner_rate_percent_sublet_paid_to_auto_owner', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='promotion_points',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_basic_cleaning_for_sublet',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_detail',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_itinerary_change_per_mile_over_30_miles',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_itinerary_change_return_to_owner',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_park_day',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_percent_sublet_paid_to_auto_owner',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_percent_sublet_paid_to_partner',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_rent_day',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_tax_1',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_tax_2',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_valet',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_valet_commission_empty_trip',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_valet_commission_fueling',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_valet_commission_itinerary_change_return',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_valet_commission_park',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_valet_commission_terminal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='airport',
            name='rate_wash',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_basic_cleaning_for_sublet',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_detail',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_itinerary_change_per_mile_over_30_miles',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_itinerary_change_return_to_owner',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_park_day',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_percent_sublet_paid_to_auto_owner',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_percent_sublet_paid_to_partner',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_rent_day',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_valet',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_valet_commission_empty_trip',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_valet_commission_fueling',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_valet_commission_itinerary_change_return',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_valet_commission_park',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_valet_commission_terminal',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
        migrations.AlterField(
            model_name='partner',
            name='rate_wash',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5),
        ),
    ]
