# Generated by Django 2.0.6 on 2018-08-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_auto_20180819_0055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='promotion_points',
            new_name='rate_promotion_points',
        ),
        migrations.RenameField(
            model_name='companydefault',
            old_name='airport_promotion_points',
            new_name='airport_rate_promotion_points',
        ),
    ]
