# Generated by Django 2.0.6 on 2018-08-23 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_auto_20180819_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('record_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_user', to='Api.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_user', to='Api.User')),
            ],
        ),
    ]
