# Generated by Django 2.0.6 on 2018-08-31 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_itinerary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sublettable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_for_rent', models.BooleanField(default=False)),
                ('fuel', models.CharField(max_length=50)),
                ('has_garage_opener', models.BooleanField(default=False)),
                ('has_ez_pass', models.BooleanField(default=False)),
                ('wash_condition', models.CharField(max_length=50)),
                ('detail_condition', models.CharField(max_length=50)),
                ('informed_cleaning', models.BooleanField(default=False)),
                ('dent_condition', models.CharField(max_length=50)),
                ('informed_condition', models.BooleanField(default=False)),
                ('condition', models.TextField()),
                ('stored_belongings', models.BooleanField(default=False)),
                ('fuel_topped_amount', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Auto')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.Itinerary')),
                ('record_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.User')),
            ],
        ),
    ]
