# Generated by Django 2.0.6 on 2018-09-11 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_sublettable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sublettable',
            name='itinerary',
        ),
    ]
