# Generated by Django 2.0.6 on 2018-09-12 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_auto_20180912_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sublettable',
            name='condition',
            field=models.TextField(default='NOT CHECKED'),
        ),
        migrations.AlterField(
            model_name='sublettable',
            name='dent_condition',
            field=models.CharField(default='NOT CHECKED', max_length=50),
        ),
        migrations.AlterField(
            model_name='sublettable',
            name='detail_condition',
            field=models.CharField(default='NOT CHECKED', max_length=50),
        ),
        migrations.AlterField(
            model_name='sublettable',
            name='fuel',
            field=models.CharField(default='NOT CHECKED', max_length=50),
        ),
        migrations.AlterField(
            model_name='sublettable',
            name='fuel_topped_amount',
            field=models.CharField(default='NOT CHECKED', max_length=50),
        ),
        migrations.AlterField(
            model_name='sublettable',
            name='wash_condition',
            field=models.CharField(default='NOT CHECKED', max_length=50),
        ),
    ]
